maximum_email: 50
minimum_password: 6
maximum_name: 60
maximum_address: 255
minimum_phone: 10
maximum_phone: 11
maximum_price: 10000000000
minimum_price: 0
maximum_quatity: 100000
minimum_quatily: 1
maximum_update_image: 5
