maximum_email: 50
minimum_password: 6
maximum_name: 60
maximum_address: 255
minimum_phone: 9
maximum_phone: 11
maximum_price: 10000000000
minimum_price: 0
maximum_quantity: 1000
minimum_quantily: 1
maximum_update_image: 5
maximum_per_page: 10
number_of_import_file: 1
maximum_top_products: 8
maximum_note: 5000
delivery_day: 2
end_status_order: 5
end_status_suggest: 2
maximum_suggest: 9000
day7_chart: 6
day10_chart: 9
day30_chart: 29
maximum_notify_message: 9
